name: clock_of_clocks_website
description: Clock of clocks website project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  property_change_notifier: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/clock_table.png
   - assets/images/lenovo_clock.png